# Generated by Django 6.0.5 on 2026-06-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0003_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='github_webhook_id',
            field=models.BigIntegerField(blank=True, help_text='GitHub hook id — set when push webhook is registered on connect.', null=True),
        ),
    ]
