# Generated by Django 6.0.5 on 2026-06-19 17:51

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0006_userprofile_github_display_name'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='CodeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, default='', help_text='Source file path; empty for some issue-only chunks.', max_length=512)),
                ('chunk_index', models.PositiveIntegerField(default=0, help_text='Order when a long patch is split into multiple chunks.')),
                ('content', models.TextField(help_text='Metadata prefix + diff or issue text that was embedded.')),
                ('source_type', models.CharField(choices=[('diff', 'Diff'), ('issue', 'Issue')], max_length=20)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, help_text='HuggingFace MiniLM-L6-v2 vector (384 dims by default).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_chunks', to='repos.commit')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_chunks', to='repos.repository')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repository', 'commit'], name='repos_codec_reposit_1670d3_idx')],
                'constraints': [models.UniqueConstraint(fields=('commit', 'file_path', 'chunk_index', 'source_type'), name='unique_code_chunk_per_commit_file_index')],
            },
        ),
    ]
